package lab.telemetryagent;

import java.io.*; import java.lang.instrument.Instrumentation; import java.lang.reflect.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.time.Instant; import java.util.*;

/** Read-only world/battle telemetry for the local dashboard. */
public final class TelemetryAgent {
  private static volatile boolean started; private TelemetryAgent() {}
  public static synchronized void agentmain(String options, Instrumentation instrumentation) {
    if (started) return; String[] values=(options==null?"":options).split(",",-1); if(values.length!=3)throw new IllegalArgumentException("Expected LOG_PATH,PORT,TAG"); started=true;
    new Thread(()->serve(Path.of(values[0]),Integer.parseInt(values[1]),values[2],instrumentation),"bridge-telemetry").start();
  }
  private static void serve(Path log,int port,String tag,Instrumentation instrumentation){try{Snapshot snapshot=new Snapshot(instrumentation);try(ServerSocket server=new ServerSocket(port,8,InetAddress.getLoopbackAddress())){write(log,"listening tag="+tag+" port="+port);while(!server.isClosed())try(Socket socket=server.accept();BufferedReader reader=new BufferedReader(new InputStreamReader(socket.getInputStream(),StandardCharsets.UTF_8));PrintWriter writer=new PrintWriter(socket.getOutputStream(),true,StandardCharsets.UTF_8)){String line;while((line=reader.readLine())!=null){if(line.trim().equalsIgnoreCase("PING"))writer.println("OK PONG TELEMETRY");else if(line.trim().equalsIgnoreCase("SNAPSHOT"))writer.println("OK SNAPSHOT_B64 "+Base64.getEncoder().encodeToString(snapshot.json().getBytes(StandardCharsets.UTF_8)));else writer.println("ERR unknown command");}}}}catch(Throwable error){started=false;write(log,"server_error="+error);}}
  private static final class Snapshot {
    final Object session; final Field battleField;
    Snapshot(Instrumentation i)throws Exception{Class<?> globals=loaded(i,"f.Ot");session=globals.getField("Z02").get(null);battleField=globals.getField("Bu");}
    String json()throws Exception{
      Object world=findField(session.getClass(),"tE0").get(session),player=findField(world.getClass(),"cy").get(world),position=findField(player.getClass(),"F61").get(player);
      int px=shortField(position,"q90"),py=shortField(position,"sj0");String map=mapKey(position),mapName=mapName(position);long money=numberField(findField(session.getClass(),"J2").get(session),"HT");
      StringBuilder players=new StringBuilder("["),trainers=new StringBuilder("["),npcs=new StringBuilder("[");Object entities=findField(world.getClass(),"yb0").get(world);
      if(entities instanceof Map<?,?> values)for(Object entity:values.values()){if(entity==null||entity==player)continue;try{Object ep=findField(entity.getClass(),"F61").get(entity);if(!map.equals(mapKey(ep)))continue;int x=shortField(ep,"q90"),y=shortField(ep,"sj0");if(Math.abs(x-px)>18||Math.abs(y-py)>18)continue;String name=name(entity);String item="{\"id\":\""+escape(String.valueOf(valuesKey(values,entity)))+"\",\"name\":\""+escape(name)+"\",\"x\":"+x+",\"y\":"+y+"}";if(entity.getClass().getName().equals("f.E41"))append(players,item);else if(entity.getClass().getName().equals("f.tT")&&trainer(entity))append(trainers,item);else append(npcs,item);}catch(Throwable ignored){}}
      close(players);close(trainers);close(npcs);String battle=battle();
      return "{\"player\":{\"map\":\""+escape(map)+"\",\"mapName\":\""+escape(mapName)+"\",\"x\":"+px+",\"y\":"+py+",\"money\":"+money+"},\"nearby\":{\"players\":"+players+",\"trainers\":"+trainers+",\"npcs\":"+npcs+"},\"battle\":"+battle+"}";
    }
    String battle()throws Exception{Object battle=battleField.get(null);if(battle==null)return "null";Object matrix=battle.getClass().getField("dO").get(battle);if(Array.getLength(matrix)<2)return "null";Object row=Array.get(matrix,1),enemy=null;for(int n=0;n<Array.getLength(row);n++)if((enemy=Array.get(row,n))!=null)break;if(enemy==null)return "null";String species=String.valueOf(enemy.getClass().getMethod("M81").invoke(enemy));int level=Byte.toUnsignedInt(findField(enemy.getClass(),"zv0").getByte(enemy)),hp=((Number)enemy.getClass().getMethod("Kh").invoke(enemy)).intValue();Object model=enemy.getClass().getField("ZU").get(enemy);int maxHp=Short.toUnsignedInt(findField(model.getClass(),"NV0").getShort(model));boolean shiny=(Boolean)enemy.getClass().getMethod("Dk0").invoke(enemy),secret=(Boolean)enemy.getClass().getMethod("dA1").invoke(enemy),wild=findField(enemy.getClass(),"d3").get(enemy).getClass().getName().equals("f.bU0");return "{\"enemy\":{\"species\":\""+escape(species)+"\",\"level\":"+level+",\"hp\":"+hp+",\"maxHp\":"+maxHp+",\"shiny\":"+shiny+",\"secretShiny\":"+secret+",\"wild\":"+wild+"}}";}
    boolean trainer(Object entity){try{Object value=findField(entity.getClass(),"av").get(entity);return value!=null&&Array.getLength(value)>0;}catch(Throwable ignored){return false;}}
    String name(Object entity){for(String method:new String[]{"Sd","Ml1"})try{return String.valueOf(entity.getClass().getMethod(method).invoke(entity));}catch(Throwable ignored){}return entity.getClass().getSimpleName();}
  }
  private static Object valuesKey(Map<?,?> map,Object value){for(Map.Entry<?,?> e:map.entrySet())if(e.getValue()==value)return e.getKey();return "";}
  private static void append(StringBuilder b,String item){if(b.length()>1)b.append(',');b.append(item);}private static void close(StringBuilder b){b.append(']');}
  private static String mapKey(Object p)throws Exception{byte a=findField(p.getClass(),"Ai").getByte(p),b=findField(p.getClass(),"Nb1").getByte(p),c=findField(p.getClass(),"ez").getByte(p);Object m=p.getClass().getMethod("WZ0").invoke(p);short id=m==null?-1:(short)m.getClass().getMethod("eA1").invoke(m);return a+":"+b+":"+c+":"+id;}private static String mapName(Object p)throws Exception{Object m=p.getClass().getMethod("WZ0").invoke(p);return m==null?"":String.valueOf(m.getClass().getMethod("U61").invoke(m));}
  private static long numberField(Object v,String n)throws Exception{return ((Number)findField(v.getClass(),n).get(v)).longValue();}private static short shortField(Object v,String n)throws Exception{return findField(v.getClass(),n).getShort(v);}private static String escape(String v){return v.replace("\\","\\\\").replace("\"","\\\"").replace("\n"," ").replace("\r"," ");}
  private static Field findField(Class<?> t,String n)throws Exception{for(Class<?> c=t;c!=null;c=c.getSuperclass())try{Field f=c.getDeclaredField(n);f.trySetAccessible();return f;}catch(NoSuchFieldException ignored){}throw new NoSuchFieldException(n);}private static Class<?> loaded(Instrumentation i,String n){for(Class<?> t:i.getAllLoadedClasses())if(t.getName().equals(n))return t;throw new IllegalStateException(n);}private static synchronized void write(Path p,String m){try{Files.writeString(p,Instant.now()+" "+m+System.lineSeparator(),StandardOpenOption.CREATE,StandardOpenOption.APPEND);}catch(Exception ignored){}}
}
