export function dashboardPage(basePath) {
  const base = JSON.stringify(basePath);
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PokeMMO Headless</title><style>
:root{color-scheme:dark;--bg:#0c1117;--panel:#151e27;--edge:#283746;--text:#eaf2f8;--muted:#8fa3b5;--red:#ed526a}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:14px Segoe UI,system-ui,sans-serif}header{height:66px;padding:0 24px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--edge)}h1{font-size:20px;margin:0;letter-spacing:.06em}.pill{padding:7px 12px;border-radius:20px;background:#202c38;color:var(--muted)}main{padding:18px;display:grid;grid-template-columns:minmax(420px,1.5fr) minmax(300px,1fr);gap:16px}.panel{background:var(--panel);border:1px solid var(--edge);border-radius:10px;padding:16px}.mapPanel{grid-row:span 2}h2{font-size:12px;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin:0 0 12px}.stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.stat{background:#101820;padding:12px;border-radius:7px}.stat b{display:block;font-size:23px;margin-top:3px}.muted{color:var(--muted)}canvas{width:100%;height:520px;background:#091017;border-radius:7px}.row{display:flex;gap:10px;align-items:end;flex-wrap:wrap}input,select,button{background:#202c38;color:var(--text);border:1px solid #385064;border-radius:5px;padding:9px;min-height:38px}button{cursor:pointer;background:var(--red);border:0;font-weight:600}button.secondary{background:#243340}label{display:grid;gap:5px;color:var(--muted)}form{display:grid;grid-template-columns:1fr 1fr auto;gap:9px;align-items:end;margin-top:12px}.entities{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.entity{background:#101820;border-radius:6px;padding:9px}.battle{border-left:4px solid var(--red)}table{width:100%;border-collapse:collapse}td{padding:7px;border-bottom:1px solid var(--edge)}#actionError{color:var(--red);margin-top:8px}@media(max-width:900px){main{grid-template-columns:1fr;padding:8px}.mapPanel{grid-row:auto}.stats{grid-template-columns:repeat(2,1fr)}canvas{height:390px}form{grid-template-columns:1fr}.row>*{flex:1 1 120px}}
</style></head><body><header><h1>POKEMMO HEADLESS</h1><span class="pill" id="connection">OFFLINE</span></header><main>
<section class="panel mapPanel"><div class="row" style="justify-content:space-between"><h2>Live surroundings</h2><span id="position" class="muted">No position</span></div><canvas id="map" width="900" height="600"></canvas><div class="row muted" style="margin-top:9px"><span>● You</span><span style="color:#58c7ff">● Player</span><span style="color:#f4b84d">● Trainer</span><span style="color:#55ce83">● NPC</span></div></section>
<section class="panel"><h2>Account & activity</h2><div id="loginState" class="muted"></div><form id="login"><label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button>LOGIN</button></form><form id="mfa" hidden><label>MFA code<input name="code" inputmode="numeric" autocomplete="one-time-code" required></label><button>VERIFY</button></form><hr style="border-color:var(--edge);margin:16px 0"><div class="row"><select id="mode"><option value="explore">Explore & map</option><option value="train">Train by level</option><option value="hunt">Hunt species</option><option value="shiny">Shiny hunt</option></select><input id="target" placeholder="Pokémon name or ID"><label>Min level<input id="levelMin" type="number" min="1" max="100" value="1"></label><label>Max level<input id="levelMax" type="number" min="1" max="100" value="100"></label><button id="start">START</button><button id="stop" class="secondary">STOP</button></div><div id="activityState" class="muted" style="margin-top:12px">Stopped</div><div id="actionError"></div></section>
<section class="panel"><h2>Current status</h2><div class="stats"><div class="stat">Money<b id="money">—</b></div><div class="stat">Poké Balls<b id="balls">—</b></div><div class="stat">Maps<b id="maps">0</b></div><div class="stat">Species IDs<b id="species">0</b></div><div class="stat">Centers<b id="centers">0</b></div></div><div id="battle" style="margin-top:12px"></div></section>
<section class="panel"><h2>Nearby</h2><div id="nearby" class="entities"></div></section><section class="panel"><h2>Pokémon Centers</h2><table id="centerTable"></table></section>
</main><script>
const BASE=${base};let state=null;const $=id=>document.getElementById(id);async function api(path,options={}){const r=await fetch(BASE+'/api/'+path,{headers:{'content-type':'application/json',...(options.headers||{})},...options});if(!r.ok){let message=await r.text();try{message=JSON.parse(message).error||message}catch{}throw new Error(message)}return r.status===204?null:r.json()}
function draw(s){const c=$('map'),g=c.getContext('2d'),tiles=s.map.visited.map(v=>v.split(',').map(Number));g.fillStyle='#091017';g.fillRect(0,0,c.width,c.height);if(!tiles.length)return;const xs=tiles.map(t=>t[0]),ys=tiles.map(t=>t[1]),minX=Math.min(...xs)-2,maxX=Math.max(...xs)+2,minY=Math.min(...ys)-2,maxY=Math.max(...ys)+2,scale=Math.max(5,Math.min(22,Math.min(c.width/(maxX-minX+1),c.height/(maxY-minY+1)))),ox=(c.width-(maxX-minX+1)*scale)/2,oy=(c.height-(maxY-minY+1)*scale)/2,pos=(x,y)=>[ox+(x-minX)*scale,oy+(y-minY)*scale];g.fillStyle='#263746';for(const[x,y]of tiles){const[p,q]=pos(x,y);g.fillRect(p,q,scale-1,scale-1)}const dots=[...(s.nearby.players||[]).map(x=>[x,'#58c7ff']),...(s.nearby.trainers||[]).map(x=>[x,'#f4b84d']),...(s.nearby.npcs||[]).map(x=>[x,'#55ce83'])];for(const[e,color]of dots){if(e.x==null)continue;const[p,q]=pos(e.x,e.y);g.fillStyle=color;g.beginPath();g.arc(p+scale/2,q+scale/2,Math.max(3,scale*.32),0,7);g.fill()}if(s.player.x!=null){const[p,q]=pos(s.player.x,s.player.y);g.fillStyle='#ed526a';g.beginPath();g.arc(p+scale/2,q+scale/2,Math.max(4,scale*.38),0,7);g.fill()}}
function render(s){state=s;$('connection').textContent=s.connection.state.toUpperCase();$('position').textContent=s.player.map?(s.player.mapName||s.player.map)+' ('+s.player.x+', '+s.player.y+')':'No position';$('money').textContent=s.player.money==null?'—':'$'+Number(s.player.money).toLocaleString();$('balls').textContent=s.inventory.balls==null?'—':s.inventory.balls;$('maps').textContent=s.survey.maps;$('species').textContent=s.survey.speciesIndexed;$('centers').textContent=s.survey.pokemonCenters;$('loginState').textContent=s.login.state.replaceAll('_',' ')+' — '+s.connection.detail;$('mfa').hidden=!s.login.mfaRequired;$('activityState').textContent=(s.activity.running?'RUNNING · ':'STOPPED · ')+(s.activity.botState||s.activity.mode)+(s.activity.destination?' · '+s.activity.destination:'')+(s.activity.lastCommand?' · '+s.activity.lastCommand:'');const e=s.battle?.enemy,wild=e?.wild===true?'Wild':e?.wild===false?'Trainer-owned':'Type unknown';$('battle').innerHTML=e?'<div class="stat battle"><span class="muted">BATTLING</span><b style="font-size:20px">'+esc(e.species)+' Lv. '+e.level+(e.shiny?' ✨ SHINY':'')+'</b><div>HP '+e.hp+' / '+e.maxHp+' · '+wild+'</div></div>':'<span class="muted">No active battle</span>';const groups=[['Players',s.nearby.players],['Trainers',s.nearby.trainers],['NPCs',s.nearby.npcs]];$('nearby').innerHTML=groups.map(([n,a])=>'<div class="entity"><b>'+n+'</b><div class="muted">'+(a.length?a.map(x=>esc(x.name||x.id||'?')).join('<br>'):'None visible')+'</div></div>').join('');$('centerTable').innerHTML=(s.survey.centers||[]).map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.status)+'</td><td>'+esc(x.map)+'</td></tr>').join('');draw(s)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}async function act(work){$('actionError').textContent='';try{return await work()}catch(e){$('actionError').textContent=e.message}}
$('login').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await act(()=>api('login',{method:'POST',body:JSON.stringify({username:f.get('username'),password:f.get('password')})}))}finally{e.target.password.value=''}};$('mfa').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await act(()=>api('mfa',{method:'POST',body:JSON.stringify({code:f.get('code')})}))}finally{e.target.code.value=''}};$('start').onclick=()=>act(()=>api('activity',{method:'POST',body:JSON.stringify({running:true,mode:$('mode').value,targetSpecies:$('target').value,levelMin:Number($('levelMin').value),levelMax:Number($('levelMax').value)})}));$('stop').onclick=()=>act(()=>api('activity',{method:'POST',body:JSON.stringify({running:false})}));setInterval(()=>api('state').then(render).catch(()=>$('connection').textContent='ERROR'),750);api('state').then(render);
</script></body></html>`;
}
